version: '3.8'
services:
  reactle:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
      - './public:/app/public'
      - './package-lock.json:/app/package-lock.json'
      - './package.json:/app/package.json'
