name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: 2.8.1
          prettier_options: --check src
          prettier_plugins: '@trivago/prettier-plugin-sort-imports prettier-plugin-tailwindcss'
